### PR TITLE
Add a property test that the generated regex is syntactically valid.

### PR DESCRIPTION
**Pull request by christophebiocca**

### CODE REVIEW

**Comment by christophebiocca** [comment]
Using quickcheck because I'm familiar with it, but proptest would probably work just as well for this.

**Comment by pemistahl** [comment]
Thanks a lot for this pull request, @christophebiocca. I'm not going to merge it now because it's actually breaking the build on Travis CI, probably because the property test is running for more than 10 minutes. At least, that's what Travis is saying. Are you able to fix this? If not, I will reject this pull request and implement some property tests myself. But your code gives a good example of how this could be accomplished, so thank you for that. :)

**Comment by christophebiocca** [comment]
So now the builds are red, but for the expected reason (the test found a counterexample).

**Comment by pemistahl** [comment]
I'm closing this pull request because it is a subset of pull request #8.

**Pull request closed without merging**
